### PR TITLE
Mouse fixes

### LINKED ISSUE #130: weird behavior of mouse click
I exclusively use Wolf with mouse, and I have noticed a weird interaction of the mouse click.

Based on my observation, a mouse click will only be registered IF i move my mouse after i click.

https://github.com/user-attachments/assets/19a2c16f-570a-46de-a348-4ac163ee9c76

https://github.com/user-attachments/assets/967bc44e-1b8b-46b5-8f32-e51fe18f1a35

I created a simple web to explain this behavior, the first video is where i demonstrate the weird behavior in Wolf environment.

Notice that after I click the mouse the web output nothing and the click is registered only after i move the mouse (on the video i use the monitor as the mouse surface to move the mouse). 
Compare the behavior with the second video where the mouse click is registered right after.

Hopefully I'm making sense, let me know if further clarification is needed!

### PR DESCRIPTION
**Pull request by ABeltramo**
In this PR:

- added user configurable `mouse_acceleration`, `v_scroll_acceleration` and `h_scroll_acceleration`, see [docs](https://games-on-whales.github.io/wolf/dev-mouse-sensitivity/user/configuration.html#_input_mouse_overrides)
- added per-user joypad override config, see [docs](https://games-on-whales.github.io/wolf/dev-mouse-sensitivity/user/configuration.html#_override_the_default_joypad_mapping)
- fixed #130

To test it out, just pull the latest from this branch:
```
ghcr.io/games-on-whales/wolf:dev-mouse-sensitivity
```

### CODE REVIEW

**Comment by AnakTeka** [comment]
Can we also add adjustable mouse scroll? (I find the scroll mouse is a bit slow)

**Comment by ABeltramo** [comment]
@AnakTeka I've added the mouse scroll setting and few other fixes (see the updated comment at the top), let me know if this works for you!

**Comment by AnakTeka** [comment]
mouse scroll setting works very well!

**Comment by ABeltramo** [comment]
Nice, thanks for confirming, I'm going to merge it then!

**Pull request merged**
